### ISSUE TITLE
PointCloudSample issue: Connection to VIPER OK, but no data acquired on necessary topic

### ISSUE THREAD

**Issue by xen20** [rubedos/viper_win#3]
My setup is as follows:

- Visual Studio Community 2019 on Windows 10.
- Thinkpad T480s on Wifi, VIPER on Ethernet via network switch.
- CVM 1.0.0.2153, Active license for CVM-Stereo.

While I have no problems running several example programs (e.g Wpf3DPointCloud, ImageStreamWpf, others) I am having an issue running the PointCloudSample program: Connection is fine, and the topics are acquired correctly ($prefix/points2) among them, but the actual Lambda doing the data processing (line 34 and on) is not being entered: it is skipped (as seen from running debug) and the program outputs nothing until disconnect. I have not modified anything aside from the address to my specific VIPER, what might be the issue?

Thanks!

**Comment by HenrikasRS** [comment]
Hello Konstantin,
I can forecast following reasons why data does not arrive:
a) No data published.  Usually not the case, but a quick check would help - ssh into VIPER using ubuntu/ubuntu user, then run the command "rostopic hz /<prefix-name>/points2" to see if topic data arrives.
b) somehow prefix is not resolved correctly. Please replace "${TopicPrefix}" with the exact VIPER prefix on line 34, e.g.

`handle.subscribe<Ros.Net.Messages.sensor_msgs.PointCloud2>("/MyViper/points2", 1, (msg) =>
...`

to see if it helps.

Let me know your progress so that I can figure out what might be the problem.

**Comment by xen20** [comment]
Hi Henrikas, thank you for replying quickly.

I have done the ssh login and checked a few topics via the given method, and you are right: `rostopic hz /VIPER/points2` returns `no new messages` . Something like `/VIPER/image_raw` instead does yield results.

Before raising this issue I have tried manually entering my TopicPrefix, which would be just too easy, don't you think? :)

Thanks again.

**Comment by HenrikasRS** [comment]
Yes of course Konstantin, I just want to leave no room for error and get into the known state before proceeding :)
I've consulted with the team and they immediately suggested that one setting may be affecting the topic. Please open dynamic configuration "/<prefix>/cvm_v4l2_camera" setting group and change "read_framerate" to something 30 or below.

**Comment by xen20** [comment]
I have done as suggested, here are the exact commands that I used ( I am new to ROS, so I wanted to be thorough ):

`rosrun dynamic_reconfigure dynparam list` to get the nodes.

`rosrun dynamic_reconfigure dynparam get /VIPER/cvm_v4l2_camera` to get camera parameters (+verify existing framerate, which was 60). Below is the original output (read_framerate is 15, as you can see):

`{'auto_gain': True, 'gamma': 220, 'auto_exposure': True, 'groups': {'auto_gain':                                                                                                                                                              True, 'gamma': 220, 'auto_exposure': True, 'parent': 0, 'sharpness': 1, 'satura                                                                                                                                                             tion': 20, 'read_framerate': 15, 'gain': 3.0, 'groups': {}, 'id': 0, 'exposure':                                                                                                                                                              156.0, 'name': 'Default', 'parameters': {}, 'brightness': 0, 'type': '', 'state                                                                                                                                                             ': True, 'white_balance': 4600, 'camera_framerate': 30, 'auto_wb': True, 'resolu                                                                                                                                                             tion': '2560x720', 'contrast': 10}, 'brightness': 0, 'sharpness': 1, 'saturation                                                                                                                                                             ': 20, 'read_framerate': 15, 'white_balance': 4600, 'camera_framerate': 60, 'gai                                                                                                                                                             n': 3.0, 'auto_wb': True, 'resolution': '2560x720', 'contrast': 10, 'exposure':                                                                                                                                                              156.0}`

`rosrun dynamic_reconfigure dynparam set /VIPER/cvm_v4l2_camera read_framerate 30` .

I have subsequently ran the PointsCloudSample, to no results. Another run of  `rostopic hz /VIPER/points2` still says there are no new messages.

Note: I doubt there is any connection, but I get the following message:  `the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'` . Device packages are also not updated.

**Comment by ArnasRS** [comment]
Hi, it is a known issue regarding the combination of read_framerate and resolution. 

For HD resolution (2560x720) read_framerate should be 8 or less, for nHD (1280x360) - 15 or less. Otherwise, `points2` will not be published, since the synchronization of topics is lost. The current VIPER SW version has optimal queue sizes, which reduces latency, but on the other hand, one has to face such issues.

I hope it helps.

**Comment by HenrikasRS** [comment]
Also regards dynamic configuration, may I suggest to use RosTools (http://apt2.rubedos.com/viper/1.0.0.2153/Rubedos.CVM.ROSTools_1.0.0.2148.zip) - just launch any of them, then connect to VIPER and then you can configure device via UI dialog (the cog icon).

**Comment by xen20** [comment]
@ArnasRS : Thanks! That solves the problem. We get data now. 

@HenrikasRS : Thanks for noting the GUI, I come from a Linux background so CLI is no issue, but of course, this is 500x faster :)
