### ISSUE TITLE
PointCloudSample issue: problems acquiring useful x y z data

### ISSUE THREAD

**Issue by xen20** [rubedos/viper_win#4]
Hello there, it's me again (Konstantin from Angular Velocity) :( .

My setup is as follows:

- Visual Studio Community 2019 on Windows 10.
- Thinkpad T480s on Wifi, VIPER on Ethernet via network switch.
- CVM 1.0.0.2153, Active license for CVM-Stereo.
- UHD graphics 620, i7 8550u.

I've been messing around with the PointCloudSample for a while now, but so far, I could not acquire any useful data: my issue is similar to the following issue: https://github.com/rubedos/viper_win/issues/2 , and I am also getting many constant values, mostly across the x and z axes. 

Setup is default (having reset all nodes, restarted). Moved the camera around rooms, changed objects, angles, etc, but no luck. 

Measured data, plots, setup picture, can be found [here.](https://drive.google.com/drive/folders/1QUSJ24PfRHemPEJOSE-8gJYUHfm6SL57?usp=sharing) Thanks!

**Comment by HenrikasRS** [comment]
Hi Konstantin, thanks for feedback.
Investigated the sample and found some problems with RGB and index incrementation, but XYZ seems to be OK. Just wanted to note a few things:
1. If X coordinate is NaN or negative, it means the point is invalid, i.e. has been discarded by algorithm. The default strategy is to ignore this point or set XYZ to 0. This is probably where you noticed many constant values.
2. Coordinates are in ROS coordinate space, which from VIPER point of view would look like: X - forward, Y - left, Z - up.
VIPER coordinate system is: X - left, Y - up, Z - forward.

I'm updating the sample code to export first frame of pointcloud to text file which can be viewed using RosTools PointCloudViewer application:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Ros.Net;
using Ros.Net.utilities;
using Rubedos.Viper.Net;

namespace PointCloudSample
{
  /// <summary>
  /// Following sample shows how to read point cloud from camera. The received data frame is described in ROS documentation:
  /// http://docs.ros.org/melodic/api/sensor_msgs/html/msg/PointCloud2.html
  ///
  /// This sample exports first frame of the pointcloud into text file that can be opened and viewed with RosTools PointCloudViewer application.
  /// </summary>
  class Program
  {
    private static readonly log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
    static void Main(string[] args)
    {
      try
      {
        var currentDir = new System.IO.FileInfo(System.Reflection.Assembly.GetEntryAssembly().Location).Directory;
        string fileName = String.Format(@"{1}\rgbd.{0}.txt", DateTime.Now.ToLongTimeString().Replace(":", "-"), currentDir);
        System.IO.FileInfo fi = new System.IO.FileInfo(fileName);

        // Specify VIPER IP here
        using (CvmDevice module = new CvmDevice("http://192.168.1.170:11311", "192.168.1.51"))
        {
          module.RosNode = "PointCloudSample";
          module.Connect();
          if (!module.IsConnected)
            throw new InvalidOperationException("Cannot connect to VIPER!");

          bool firstFrame = true;
          NodeHandle handle = new NodeHandle();
          handle.subscribe<Ros.Net.Messages.sensor_msgs.PointCloud2>("${TopicPrefix}/points2", 1, (msg) =>
          {
            if (msg == null)
              return;
            if (firstFrame)
            {
              firstFrame = false;
              log.InfoFormat("Received point cloud {0} x {1}", msg.width, msg.height);
              log.InfoFormat("Is dense: {0}", msg.is_dense ? "Yes" : "No");
              log.InfoFormat("Point step: {0}", msg.point_step);
              log.InfoFormat("Is bigendian: {0}", msg.is_bigendian ? "Yes" : "No");
              log.InfoFormat("Row step: {0}", msg.row_step);
              log.InfoFormat("Total data: {0}", msg.data.Length);
              // More information about PointField structure: http://docs.ros.org/melodic/api/sensor_msgs/html/msg/PointField.html
              foreach (var field in msg.fields)
                log.InfoFormat("{0} @ {1} x {3}, type id {2}", field.name, field.offset, field.datatype, field.count);

              using (System.IO.StreamWriter writer = new System.IO.StreamWriter(fi.FullName))
              {
                writer.WriteLine("{0}", msg.width * msg.height);
                writer.WriteLine("Grid size: {0} x {1}", msg.width, msg.height);
                writer.WriteLine(@"X; Y;  Z;  R;  G;  B;");

                for (int j = 0; j < msg.height; j++)
                  for (int i = 0; i < msg.row_step; i += (int)msg.point_step)
                  {
                    int ix = j * (int)msg.row_step + i;
                    float x = BitConverter.ToSingle(msg.data, ix);
                    float y = BitConverter.ToSingle(msg.data, ix + 4);
                    float z = BitConverter.ToSingle(msg.data, ix + 8);
                    byte r = msg.data[ix + 16];
                    byte g = msg.data[ix + 17];
                    byte b = msg.data[ix + 18];

                    if (float.IsNaN(x) || x < 0)
                    {
                      writer.WriteLine(String.Format(System.Globalization.CultureInfo.InvariantCulture, @"{0:0.000}; {1:0.000};  {2:0.000};  {3};  {4};  {5};", 0, 0, 0, 0, 0, 0));
                    }
                    else
                      // NOTE: coordinates are in ROS space. Converting to VIPER space using transform: X->Z, Y->Z, Z->Y
                      writer.WriteLine(String.Format(System.Globalization.CultureInfo.InvariantCulture, @"{0:0.000}; {1:0.000};  {2:0.000};  {3};  {4};  {5};", y, z, x, r, g, b));
                  }
              }
            }
          });

          System.Threading.Thread.Sleep(30 * 1000); // 30 secs
          module.Disconnect();
        }
      }
      catch (Exception ex)
      {
        log.Error(ex);
      }
    }
  }
}
```

**Comment by xen20** [comment]
Hello Henrikas, 
The new code builds and runs fine, however point cloud viewer (tools/pointcloudviewer) cannot parse the output file. Are there some settings that I must tweak prior to loading it in? I have played around with point cloud properties, but that doesn't seem to help it.
Here is the output: [pointcloud](https://drive.google.com/open?id=1PcLvAsReW0pKzLx55_aIKAMSrSCXs0Fj)

Have a good May 1st.

**Comment by HenrikasRS** [comment]
It looks like exported non-zero numbers have comas instead of dots and
zeros have dots. It's best to use CultureInvariant, but since your regional
settings are expecting comas in PointCloudViewer, I think it's best to fix
the zeros:

writer.WriteLine(@"0,000; 0,000;  0,000;  0;  0;  0;");

**Comment by xen20** [comment]
That works :) the resulting image is as expected.

The commas and dots thing... yeah. It's been annoying more than once already, should have kept it in the back of my mind in this case.

Thanks for the help so far. I will see what can be made of the data on Thursday.
